# Site settings
title: Benjamin Badejo
description: Ben Badejo - New York, NY
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benbadejo.com" # the base hostname & protocol for your site e.g. https://willianjusten.com.br

# User settings
username: Ben Badejo
# user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: New York, NY 
email: ben@benbadejo.com
# twitter_username: lorem_ipsum
# instagram_username: mauricio.urraco
# linkedin_username: murraco
# github_username:  murraco
# facebook_username: notprovided
phone_number: +1-212-203-7591
linkedin_username: benjaminbadejo
cv_url: https://www.dropbox.com/scl/fi/gn6i8jr82uhuw8hsag4g6/Ben-Badejo-Resume-2025-02-03.pdf?rlkey=yyh4mmrmmnprqvjvq91u8mpq2&st=c3fxdymu&dl=0
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

